/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_AgeGenderCheck */

#ifndef _Included_org_opencv_AgeGenderCheck
#define _Included_org_opencv_AgeGenderCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_AgeGenderCheck
 * Method:    GetAgeAndSex
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_opencv_AgeGenderCheck_GetAgeAndSex
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
