/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.kaldi;

public class SpkModel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SpkModel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpkModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VoskJNI.delete_SpkModel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SpkModel(String model_path) {
    this(VoskJNI.new_SpkModel(model_path), true);
  }

}
